alter table device_data add unique index (sn);
alter table device_data add index (order_id);
alter table device_data add index (test_result);
alter table device_data add index (factory);
alter table device_data add index (device);
alter table device_data add index (invalid);
alter table device_data add index (receive_time);
alter table product_order add index (factory);
alter table product_order add index (device);
alter table product_order add index (state);
alter table product_order add index (username);